### ISSUE TITLE
ILPAccount Payment Pointer mapping

### ISSUE THREAD

**Issue by matdehaast** [coilhq/rafiki#47]
Currently the assumption has been made that there is a 1-1 mapping between an ILPAccount and a Payment Pointer. This issue is to determine if this is what we want.

**Comment by kincaidoneil** [comment]
I don't think we should make assumptions about this; e.g., so multiple Open Payments accounts could receive into the same Interledger account.

The one assumption that I've made at least is: there's some user/identity that controls one (or more) Open Payments accounts, one (or more) Interledger accounts, and the mappings between them. So, it'd be relatively simple to change it from 1:1 to many:1 or many:many, as long as they're all managed by the same user/identity. Is that what you were thinking?

**Comment by matdehaast** [comment]
I'm going to close this for now as the discussion has moved to a higher level. Thanks @kincaidoneil that makes sense
