### ISSUE TITLE
Webmonetization Architecture

### ISSUE THREAD

**Issue by matdehaast** [coilhq/rafiki#48]
The goal of this issue is to discuss and come to a consensus of how to architect Webmonetization within Rafiki.  I want us to first begin by determining and agreeing what the end user (operator) will want and then based on that we can delve into how best to implement this.

As a starting point I propose a few User Stories

1. I as an End User want to be able to see my webmonetization earnings segmented by time.
2. I as an End User want to be able to see my webmonetization earnings per session.
3. I as an End User want to be able to see every single packet for webmonetization

**Comment by sentientwaffle** [comment]
> I as an End User want to be able to see my webmonetization earnings per session.

The extension doesn't really have server-identifiable 'sessions' due to anonymous tokens.
