### ISSUE TITLE
docs: Contributing guidelines

### ISSUE THREAD

**Issue by cairin** [coilhq/rafiki#50]
- [x] Move the contribution guidelines out of the readme.
- [x] Clean up the readme.

**Comment by vladimirfomene** [comment]
Hello @cairin, is this something a new contributor like me can work on?

**Comment by cairin** [comment]
Hey @vladimirfomene, thanks for your enthusiasm to contribute!

This is something the internal team will work on as it will be necessary to guide new collaborators (like yourself) on how to collaborate.
